### ISSUE TITLE
Support for Entity Framework Core 6.0.10

### ISSUE THREAD

**Issue by cmateescu93** [danielgerlag/workflow-core#1126]
We are using Workflow Core with WorkflowCore.Providers.Redis package. We recently updated our nuget packages and we tried upgrading to Entity Framework Core 6.0.10. 
However, when we upgrade to Entity Framework Core 6.0.10, we discovered that we are getting the following error when trying to connect to the same Redis server that we were using before:

WorkflowCore.Services.BackgroundTasks.RunnablePoller [Error] [RequestId: Connection: SpanId: TraceId: ParentId:] The specified endpoint is not defined (Parameter 'endpoint')
System.ArgumentException: The specified endpoint is not defined (Parameter 'endpoint')
   at StackExchange.Redis.ConnectionMultiplexer.GetServer(EndPoint endpoint, Object asyncState) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1474
   at RedLockNet.SERedis.RedLock.GetHost(IConnectionMultiplexer cache)
   at RedLockNet.SERedis.RedLock.UnlockInstanceAsync(RedisConnection cache)
   at RedLockNet.SERedis.RedLock.UnlockAsync()
   at RedLockNet.SERedis.RedLock.AcquireAsync()
   at RedLockNet.SERedis.RedLock.StartAsync()
   at RedLockNet.SERedis.RedLock.CreateAsync(ILogger`1 logger, ICollection`1 redisCaches, String resource, TimeSpan expiryTime, Nullable`1 waitTime, Nullable`1 retryTime, Nullable`1 cancellationToken)
   at RedLockNet.SERedis.RedLockFactory.CreateLockAsync(String resource, TimeSpan expiryTime)
   at WorkflowCore.Providers.Redis.Services.RedisLockProvider.AcquireLock(String Id, CancellationToken cancellationToken)
   at WorkflowCore.Services.BackgroundTasks.RunnablePoller.PollWorkflows()

Did anyone else experience this issue? It looks like the StackExchange.Redis package that WorkflowCore.Providers.Redis is using hasn't been updated in a very long time. Can this be a cause, can we update that package?

Or do we have to write the connection to redis in a different way? We are using a simple connection string we are not using any connection options.

Thank you in advance!

**Comment by ssougnez** [comment]
Hello,

I'm using wfc 3.8.1 along with .NET 6.0.10 and everything works as expected for me.
Here is how I configure it:

```
services.AddWorkflow(options =>
{
    options.UseSqlServer(configuration.GetConnectionString(Constants.ConnectionString.WorkflowCore), true, true);
    options.UseRedisLocking($"{settings.Redis.Host}:{settings.Redis.Port}");
    options.UseRedisQueues($"{settings.Redis.Host}:{settings.Redis.Port}", $"{settings.Redis.Prefix}_WF_");
});
```

Hope it helps/

**Comment by cristinamateescu93** [comment]
@ssougnez Can you tell me what version of redis you have? I tried configuring the same as you did and still not working :(

**Comment by ssougnez** [comment]
Hi,

It works on 3.2.100 (windows) and 6.0.9 (Linux).
