### ISSUE TITLE
MongoDb Persistence provider issue

### ISSUE THREAD

**Issue by Kollisto** [danielgerlag/workflow-core#136]
Hi. I'm using MongoDb Persistence provider and run to an issue
`System.FormatException
  HResult=0x80131537
  Message=An error occurred while deserializing the ExecutionPointers property of class WorkflowCore.Models.WorkflowInstance: An error occurred while deserializing the PersistenceData property of class WorkflowCore.Models.ExecutionPointer: Unknown discriminator value 'ControlPersistenceData'.
  Source=MongoDB.Driver
  StackTrace:
   at MongoDB.Driver.Linq.MongoQueryProviderImpl`1.Execute(Expression expression)
   at MongoDB.Driver.Linq.MongoQueryableImpl`2.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at eve.workflow.Services.MongoPersistenceProvider.<GetWorkflowInstances>d__17.MoveNext() in D:\Projects\eve-dam\src\workflow\eve.workflow\Services\MongoPersistenceProvider.cs:line 137

Inner Exception 1:
FormatException: An error occurred while deserializing the PersistenceData property of class WorkflowCore.Models.ExecutionPointer: Unknown discriminator value 'ControlPersistenceData'.

Inner Exception 2:
BsonSerializationException: Unknown discriminator value 'ControlPersistenceData'.`

`{MongoDB.Bson.BsonSerializationException: Unknown discriminator value 'ControlPersistenceData'.
   at MongoDB.Bson.Serialization.BsonSerializer.LookupActualType(Type nominalType, BsonValue discriminator)
   at MongoDB.Bson.Serialization.Conventions.ObjectDiscriminatorConvention.GetActualType(IBsonReader bsonReader, Type nominalType)
   at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.DeserializeDiscriminatedValue(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize(IBsonSerializer serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeMemberValue(BsonDeserializationContext context, BsonMemberMap memberMap)}`

On the moment when I try to get a workflow instance. Can you please check it?
Thanks,
Kolisto

**Comment by danielgerlag** [comment]
Hi Kolisto,

I'm not able to reproduce this error.  We also have a number of automated integration tests that run against a real MongoDB as part of the build process.  `Can you confirm the versions of all the WorkflowCore and MongoDB libraries you are using?`

Thanks

**Comment by danielgerlag** [comment]
Hi,

I discovered the issue with the MongoDB provider when you have nested classes in your data object.  I have deployed new Nuget packages, please update all you packages and let me know if that resolves it.

**Comment by Kollisto** [comment]
Hi danielgerlag,

Thank you, the issue about nested classes in the object is resolved with the latest update. But still I receive an error ("Unknown discriminator value 'ControlPersistenceData'") when I start my application again and it tries to restore Persistent data from db.

Also I've noticed that events processing with MongoDb persistent provider is very slow. It takes at least 5 minutes for the changes to be processed after I PublishUserAction. Do you know how to speed up this process?

Thank you

**Comment by danielgerlag** [comment]
I can't reproduce either of these issues.  Could you share some project code that is affected by this?

**Comment by Kollisto** [comment]
I attached the project for you to reproduce the issue. 
"An error occurred while deserializing the ExecutionPointers property of class WorkflowCore.Models.WorkflowInstance: An error occurred while deserializing the PersistenceData property of class WorkflowCore.Models.ExecutionPointer: Unknown discriminator value 'ControlPersistenceData'."
![issue](https://user-images.githubusercontent.com/38946374/39861965-f7600dee-544a-11e8-8a21-17819d9729ab.png)
[DigiWorkflow.zip](https://github.com/danielgerlag/workflow-core/files/1991093/DigiWorkflow.zip)

**Comment by danielgerlag** [comment]
I'm still unable to reproduce that error with this source.  Did you perhaps persist a workflow with your custom serializer at an earlier date and now you have an incompatible instance in your local DB?

**Comment by wladioh** [comment]
Hi guys, I'm having the same problem. 
I created a little WebApp to reproduce this problem. (is attached below)

[Work.zip](https://github.com/danielgerlag/workflow-core/files/2073723/Work.zip)

To reproduce this error follow the steps bellow:
1- Start Application 
2- Send a post `http://localhost:{port}/api/values` with some id on body `"SOMEID"`
3- Stop application
4- Start Application again. 

Then the error occur.

Lib versions

Microsoft.AspNetCore.All - 2.0.8
WorkflowCore - 1.6.3
WorkflowCore.Persistence.MongoDB -1.6.2

Mongo Version - 3.4.9

**Comment by danielgerlag** [comment]
I have deployed a new version of the mongo provider, could you upgrade and let me know if that fixes it?

**Comment by wladioh** [comment]
@danielgerlag the new version fixed this bug.

Thanks... You are making a big job. =)

**Comment by obushakv** [comment]
Hi. I have the same problem with IteratorPersistenceData:

My executionPointer:
     {
            "_id" : "80d6be4e-0a7f-4e7b-b3e3-2a2d68fc1bbc", 
            "StepId" : NumberInt(0), 
            "Active" : true, 
            "PersistenceData" : {
                "_t" : "IteratorPersistenceData", 
                "ChildrenActive" : true, 
                "Index" : NumberInt(0)
            }, 
            "StartTime" : "2022-07-08T12:43:36.727666Z", 
            "EventPublished" : false, 
            "ExtensionAttributes" : {

            }, 
            "RetryCount" : NumberInt(0), 
            "Children" : [
                "ec3a24ed-8257-4d6c-9018-be813eeecec8", 
                "59a79cf0-ffbe-4ef3-ad45-906b9b08b5b1", 
                "c4571475-2364-4bd9-b681-17d0acbb72df"
            ], 
            "Status" : "Running", 
            "Scope" : [

            ]
        }, 

In fact worklow instance can not be parsed in case any of it's executionPointers contains       
 "_t" : "IteratorPersistenceData"


System.FormatException
  HResult=0x80131537
  Message=An error occurred while deserializing the ExecutionPointers property of class WorkflowCore.Models.WorkflowInstance: An error occurred while deserializing the PersistenceData property of class WorkflowCore.Models.ExecutionPointer: Unknown discriminator value 'IteratorPersistenceData'.
  Source=MongoDB.Bson
  StackTrace:
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeMemberValue(BsonDeserializationContext context, BsonMemberMap memberMap)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Driver.Core.Operations.CursorBatchDeserializationHelper.DeserializeBatch[TDocument](RawBsonArray batch, IBsonSerializer`1 documentSerializer, MessageEncoderSettings messageEncoderSettings)
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.CreateFirstCursorBatch(BsonDocument cursorDocument)
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.CreateCursor(IChannelSourceHandle channelSource, BsonDocument commandResult)
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.<ExecuteAsync>d__117.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MongoDB.Driver.Core.Operations.FindOperation`1.<ExecuteAsync>d__117.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MongoDB.Driver.Core.Operations.FindOperation`1.<ExecuteAsync>d__116.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MongoDB.Driver.OperationExecutor.<ExecuteReadOperationAsync>d__3`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MongoDB.Driver.MongoCollectionImpl`1.<ExecuteReadOperationAsync>d__94`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MongoDB.Driver.MongoCollectionImpl`1.<UsingImplicitSessionAsync>d__102`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WorkflowService.DAL.Services.MongoDbPersistenceProvider.<GetWorkflowInstance>d__11.MoveNext() in C:\Users\user\work\workflow-service\src\WorkflowService.DAL\Services\MongoDbPersistenceProvider.cs:line 132

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
FormatException: An error occurred while deserializing the PersistenceData property of class WorkflowCore.Models.ExecutionPointer: Unknown discriminator value 'IteratorPersistenceData'.

Inner Exception 2:
BsonSerializationException: Unknown discriminator value 'IteratorPersistenceData'.


Thank's.
