### ISSUE TITLE
Race condition: modified enumeration

### ISSUE THREAD

**Issue by fubar-coder** [danielgerlag/workflow-core#264]
In function `WorkflowInstanceExtensions.GetOpenUserActions` I (once) got an exception about a modified collection during enumeration while enumerating `workflow.ExecutionPointers`.

**Comment by danielgerlag** [comment]
Do you perhaps have the stack trace from your logs?

**Comment by fubar-coder** [comment]
For the `GetOpenUserActions` function:

```text
WorkflowCore.IntegrationTests.Scenarios.RetrySagaWithUserTaskScenario.Scenario

System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at WorkflowCore.Models.WorkflowInstanceExtensions.GetOpenUserActions(WorkflowInstance workflow) in D:\OpenSource\workflow-core\src\extensions\WorkflowCore.Users\ServiceExtensions\WorkflowInstanceExtensions.cs:line 14
   at WorkflowCore.IntegrationTests.Scenarios.RetrySagaWithUserTaskScenario.<WaitForUserStepAsync>d__5.MoveNext() in D:\OpenSource\workflow-core\test\WorkflowCore.IntegrationTests\Scenarios\RetrySagaWithUserTaskScenario.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WorkflowCore.IntegrationTests.Scenarios.RetrySagaWithUserTaskScenario.<WaitForDifferentUserStepAsync>d__4.MoveNext() in D:\OpenSource\workflow-core\test\WorkflowCore.IntegrationTests\Scenarios\RetrySagaWithUserTaskScenario.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WorkflowCore.IntegrationTests.Scenarios.RetrySagaWithUserTaskScenario.<Scenario>d__3.MoveNext() in D:\OpenSource\workflow-core\test\WorkflowCore.IntegrationTests\Scenarios\RetrySagaWithUserTaskScenario.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

I'm currently unable to determine where the collection gets modified during the enumeration, but you can test it with a test that repeatedly calls `await new RetrySagaWithUserTaskScenario().Scenario()`.

I also had to modify `RetrySagaWithUserTaskScenario`.

Repeatedly running `RetrySagaWithUserTaskScenario` has also caused the following issues:

- `userOptions` having 0 or more than 1 element
- `Event1Fired` having a final value of 4
- `NullReferenceException` in the `GetOpenUserActions` function
- `InvalidOperationException` in the `GetOpenUserActions` function
- `Expected object to be Complete, but found Runnable.`

My assumption is, that it's a race condition. To get past the `userOptions` problem, return from the `RetrySagaWithUserTaskScenario.Scenario` function when it has the wrong value.

I can only guess that the data object value is wrong, because the corresponding task updating the value is executed multiple times for the same workflow instance.

# RetrySagaWithUserTaskScenario.cs

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;

using WorkflowCore.Interface;
using WorkflowCore.Models;
using Xunit;
using FluentAssertions;
using System.Linq;
using System.Threading.Tasks;
using WorkflowCore.Testing;
using WorkflowCore.Users.Models;

using Xunit.Abstractions;

namespace WorkflowCore.IntegrationTests.Scenarios
{
    public class RetrySagaWithUserTaskScenario : WorkflowTest<RetrySagaWithUserTaskScenario.Workflow, RetrySagaWithUserTaskScenario.MyDataClass>
    {
        private readonly ITestOutputHelper _output;

        public class MyDataClass
        {
            public int Event1Fired;
            public int Event2Fired;
            public int Event3Fired;
            public int TailEventFired;
            public int Compensation1Fired;
            public int Compensation2Fired;
            public int Compensation3Fired;
            public int Compensation4Fired;
        }

        public class Workflow : IWorkflow<MyDataClass>
        {
            public string Id => "RetrySagaWithUserTaskWorkflow";
            public int Version => 1;
            public void Build(IWorkflowBuilder<MyDataClass> builder)
            {
                builder
                    .StartWith(context => ExecutionResult.Next())
                    .CompensateWith(context => ((MyDataClass)context.Workflow.Data).Compensation1Fired++)
                    .Saga(x => x
                        .StartWith(context => ExecutionResult.Next())
                            .CompensateWith(context => ((MyDataClass)context.Workflow.Data).Compensation2Fired++)
                        .UserTask("prompt", data => "assigner")
                            .WithOption("a", "Option A")
                                .Do(wb => wb
                                    .StartWith(context => ExecutionResult.Next())
                                    .Then(context =>
                                    {
                                        ((MyDataClass)context.Workflow.Data).Event1Fired++;
                                        if (((MyDataClass)context.Workflow.Data).Event1Fired < 3)
                                            throw new Exception();
                                        ((MyDataClass)context.Workflow.Data).Event2Fired++;
                                    })
                                        .CompensateWith(context => ((MyDataClass)context.Workflow.Data).Compensation3Fired++)
                                    .Then(context => ((MyDataClass)context.Workflow.Data).Event3Fired++)
                                        .CompensateWith(context => ((MyDataClass)context.Workflow.Data).Compensation4Fired++)
                                )
                    )
                    .OnError(WorkflowErrorHandling.Retry, TimeSpan.FromSeconds(1))
                    .Then(context => ((MyDataClass)context.Workflow.Data).TailEventFired++);
            }
        }

        public RetrySagaWithUserTaskScenario(ITestOutputHelper output)
        {
            _output = output;
            Setup();
        }

        [Fact]
        public async Task Scenario()
        {
            _output.WriteLine("Test started");
            Debug.WriteLine("Test started");

            var data = new MyDataClass();
            var workflowId = StartWorkflow(data);
            var instance = await Host.PersistenceStore.GetWorkflowInstance(workflowId);

            string oldUserOptionKey = null;
            for (var i = 0; i != 3; ++i)
            {
                var userOptions = await WaitForDifferentUserStepAsync(instance, TimeSpan.FromSeconds(1), oldUserOptionKey);
                userOptions.Count.Should().Be(1);

                var userOption = userOptions.Single();
                userOption.Prompt.Should().Be("prompt");
                userOption.AssignedPrincipal.Should().Be("assigner");
                userOption.Options.Count.Should().Be(1);

                var selectionOption = userOption.Options.Single();
                selectionOption.Key.Should().Be("Option A");
                selectionOption.Value.Should().Be("a");
                await Host.PublishUserAction(userOption.Key, string.Empty, selectionOption.Value);

                oldUserOptionKey = userOption.Key;
            }

            WaitForWorkflowToComplete(workflowId, TimeSpan.FromSeconds(30));

            GetStatus(workflowId).Should().Be(WorkflowStatus.Complete);

            UnhandledStepErrors.Count.Should().Be(2);
            data.Event1Fired.Should().Be(3);
            data.Event2Fired.Should().Be(1);
            data.Event3Fired.Should().Be(1);
            data.Compensation1Fired.Should().Be(0);
            data.Compensation2Fired.Should().Be(2);
            data.Compensation3Fired.Should().Be(2);
            data.Compensation4Fired.Should().Be(0);
            data.TailEventFired.Should().Be(1);

            _output.WriteLine("Test finished");
            Debug.WriteLine("Test finished");
        }

        private static async Task<IReadOnlyCollection<OpenUserAction>> WaitForDifferentUserStepAsync(
            WorkflowInstance instance,
            TimeSpan timeout,
            string oldUserActionKey = null)
        {
            var startTime = DateTime.UtcNow;

            while (DateTime.UtcNow - startTime <= timeout)
            {
                var userActions = await WaitForUserStepAsync(instance);

                if (oldUserActionKey != null && userActions.Any(x => x.Key == oldUserActionKey))
                {
                    continue;
                }

                return userActions;
            }

            return Array.Empty<OpenUserAction>();
        }

        private static async Task<IReadOnlyCollection<OpenUserAction>> WaitForUserStepAsync(WorkflowInstance instance)
        {
            var delayCount = 200;
            var openActions = instance.GetOpenUserActions()?.ToList();
            while ((openActions?.Count ?? 0) == 0)
            {
                await Task.Delay(TimeSpan.FromMilliseconds(10));
                openActions = instance.GetOpenUserActions()?.ToList();
                if (delayCount-- == 0)
                {
                    break;
                }
            }

            return openActions;
        }
    }
}
```

# RepeatedRetrySagaWithUserTaskScenario

```csharp
using System;

using Xunit;

using System.Linq;
using System.Threading.Tasks;

using Xunit.Abstractions;

namespace WorkflowCore.IntegrationTests.Scenarios
{
    public class RepeatedRetrySagaWithUserTaskScenario
    {
        private readonly ITestOutputHelper _output;

        public RepeatedRetrySagaWithUserTaskScenario(ITestOutputHelper output)
        {
            _output = output;
        }

        [Fact]
        public async Task Scenario()
        {
            for (var i = 0; i != 100; ++i)
            {
                await new RetrySagaWithUserTaskScenario(_output).Scenario();
            }
        }
    }
}
```

**Comment by quinvit** [comment]
Is there any update on this issue please?
