### ISSUE TITLE
Can we combine UseElasticsearch with Postgresql

### ISSUE THREAD

**Issue by oblin** [danielgerlag/workflow-core#342]
use like this:

            services.AddWorkflow(config => {
                config.
                    UsePostgreSQL(@"Server=localhost;Port=5432;Database=workflow;User Id=postgres;Password=password;", true, true);
                config.UseElasticsearch(new Nest.ConnectionSettings(new Uri("http://localhost:9200")), "indexname");
                    }
            );
use PostgreSQL as database and elasticsearch for indexing.

This will works without error, but it will return empty every search like this:
```
            var searchProvice = serviceProvider.GetService<ISearchIndex>();
            var ids = searchProvice.Search("Status", 0, 10, StatusFilter.Equals(WorkflowStatus.Complete)).Result;
```

Please help, thanks in adv.

**Comment by danielgerlag** [comment]
Yes that should work, can you see any errors in the logs? Which version of Elasticsearch are you using?

**Comment by oblin** [comment]
elasticsearch version 7.2
Execute following statement will show error: 
`System.AggregateException: 'One or more errors occurred. (Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Int64' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
...
`

**Comment by danielgerlag** [comment]
Which class logged that error?

**Comment by oblin** [comment]
While invoke Search method:
Get Service provider by:
`            var searchprovice = serviceprovider.getservice<isearchindex>();
`
And then:
` 
            var page = searchprovice.search("", 0, 10, statusfilter.equals(workflowstatus.complete)).result;
`
Here is where error happened.

**Comment by danielgerlag** [comment]
The log should include the class name that raised the exception?

**Comment by oblin** [comment]
full log:
`
Unhandled Exception: System.AggregateException: One or more errors occurred. (Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Int64' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'hits.total.value', line 1, position 113.) ---> Elasticsearch.Net.UnexpectedElasticsearchClientException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Int64' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'hits.total.value', line 1, position 113. ---> Elastic.Internal.JsonNet.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Int64' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'hits.total.value', line 1, position 113.
   at Elastic.Internal.JsonNet.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Elastic.Internal.JsonNet.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Elastic.Internal.JsonNet.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Elastic.Internal.JsonNet.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Elastic.Internal.JsonNet.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Elastic.Internal.JsonNet.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Elastic.Internal.JsonNet.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Elastic.Internal.JsonNet.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Elastic.Internal.JsonNet.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Elastic.Internal.JsonNet.JsonSerializer.Deserialize[T](JsonReader reader)
   at Nest.InternalSerializer.DeserializeAsync[T](Stream stream, CancellationToken cancellationToken)
   at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
   at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType, CancellationToken cancellationToken)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.DispatchAsync[TRequest,TQueryString,TResponse,TResponseInterface](TRequest request, CancellationToken cancellationToken, Func`3 responseGenerator, Func`4 dispatch)
   at WorkflowCore.Providers.Elasticsearch.Services.ElasticsearchIndexer.Search(String terms, Int32 skip, Int32 take, SearchFilter[] filters)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ConsoleUserWorkflow.Program.Main(String[] args) in D:\Practices\Others\ConsoleWorkflow\ConsoleUserWorkflow\Program.cs:line 52
`

**Comment by danielgerlag** [comment]
Are you able to attach your project that reproduces this?
