### ISSUE TITLE
workflow-core SqlServer persistence currently doesn't work on EF core 3.0

### ISSUE THREAD

**Issue by ThomasBergholdWieser** [danielgerlag/workflow-core#413]
workflow-core uses 

Microsoft.EntityFrameworkCore.Design 2.1.0

which has breaking changes going up to 3.0.0 version. When starting a fresh project using SqlServer as Persistency provider, the app will crash with:

```System.AggregateException: One or more errors occurred. (Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasIndex(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Object>>)'.)
 ---> System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasIndex(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Object>>)'.
   at WorkflowCore.Persistence.EntityFramework.Services.WorkflowDbContext.OnModelCreating(ModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at WorkflowCore.Persistence.EntityFramework.Services.EntityFrameworkPersistenceProvider.EnsureStoreExists()
   at WorkflowCore.Services.WorkflowHost.StartAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()```

The reason is this Breaking change:
https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md#forsqlserverhasindex-replaced-with-hasindex

**Comment by ssm-dev** [comment]
the same problem :-(

**Comment by ericwp** [comment]
The same problem when we upgraded to .net core 3.0. 
Is there any plan to upgrade workflow-core to core 3.0? If not we must to stop our upgrade  :-(

**Comment by ThomasBergholdWieser** [comment]
Just a heads up for you guys with the same problem, right now you can just clone the source and include the 2 needed projects directly into your source without needing any other adjustments until this gets fixed. As we are still in early development phase, this is a feasable workaround for us.

**Comment by ericwp** [comment]
@ThomasBergholdWieser Thanks for your feedback :-)

**Comment by danielgerlag** [comment]
Just to be clear, this is not a .net core 3.0 issue... it is an EF core 3.0 issue.  There is no reason you can't still use EF core 2 with .net core 3.

**Comment by ericwp** [comment]
@danielgerlag  Thanks for your great work and feedback :-). As you point out, that caused by WorkflowCore.Persistence.SqlServer dependency “Microsoft.EntityFrameworkCore.SqlServer (>= 2.1.0)" which reference the latest packages(3.0) , same dependencies in WorkflowCore.Persistence.EntityFramework "Microsoft.EntityFrameworkCore (>= 2.1.0)" and "Microsoft.EntityFrameworkCore.Relational (>= 2.1.0)". That would be better you can limit the large version in packages. That would be a fast fix I guess. Also I can package it in my local to wait new version release.

**Comment by SevastianGioanca** [comment]
@danielgerlag Hi! 
Could you please let us know if you have any plans to upgrade to .NET Core 3.0 (or 3.1)? 
Thank you!

**Comment by danielgerlag** [comment]
@SevastianGioanca WorkflowCore does not target .Net Core, it targets .Net Standard 2 and .Net Standard 2 libraries can run on applications that target .Net Core 3.0

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/pull/445

**Comment by danielgerlag** [comment]
We will have to fork the EF providers for EF 3 and EF 2

**Comment by Viktor-36** [comment]
> 
> 
> Just a heads up for you guys with the same problem, right now you can just clone the source and include the 2 needed projects directly into your source without needing any other adjustments until this gets fixed. As we are still in early development phase, this is a feasable workaround for us.

I used same solution for now and it works fine. You only need to update EF Core to version 3.0.

**Comment by olegkap** [comment]
> > Just a heads up for you guys with the same problem, right now you can just clone the source and include the 2 needed projects directly into your source without needing any other adjustments until this gets fixed. As we are still in early development phase, this is a feasable workaround for us.
> 
> I used same solution for now and it works fine. You only need to update EF Core to version 3.0.

Same for me, I copied `WorkflowCore.Persistence.SqlServer` and `WorkflowCore.Persistence.EntityFramework` projects to my solution and refernce them.
The only few updates I made is to change target  ".NET Standart 2.1" and repalce `UseSqlServerIdentityColumn` with `UseIdentityColumn`

**Comment by cyyeap** [comment]
@olegkap and @Viktor-36's solution works, wonder if we make a pull request with this solution. Would @danielgerlag accept it?

We have many microservices that are using EF core 3.0, downgrading and re-upgrading them will be painful.

**Comment by danielgerlag** [comment]
You can still use EF core 2 with .Net core 3.  Are there specific features of EF core 3 you need?  
The problem with upgrading the EF core 3, is that it will no longer be compatible with .NET framework (only .NET core).  So we have to either fork all the EF projects to support both, or move away from EF to another ORM that has better cross platform support.

**Comment by danielgerlag** [comment]
It looks like there will be a release of EF Core 3 that targets .NET Standard 2.0...
https://github.com/aspnet/EntityFrameworkCore/issues/18141#issuecomment-542798580
I think we should wait for that to be released.
