### ISSUE TITLE
[Question] PostgreSQL doesn't use standard naming conventions?

### ISSUE THREAD

**Issue by phillip-haydon** [danielgerlag/workflow-core#500]
I'm curious to know why standard naming conventions weren't used for PostgreSQL? It make's it a real pain to query the database directly.

**Comment by danielgerlag** [comment]
I would caution you to not couple directly to the persistence schema, as it may change without notice and break your coupling, it is an internal implementation detail.  If you have a different preference for naming, you may implement your own persistence provider according to your needs... However, if your use case is to query workflow states, rather hook into the [life cycle events](https://github.com/danielgerlag/workflow-core/releases/tag/1.6.9) or use the [elastic search plugin](https://github.com/danielgerlag/workflow-core/tree/master/src/providers/WorkflowCore.Providers.Elasticsearch).

**Comment by phillip-haydon** [comment]
Hey, 

I'm evaluating WFC because I'm currently using Windows Workflow and need a new solution that runs on .NET Core, so far I love WFC & the documentation you've done, so I'm trying to set it up, see how it works, etc, and figure out how I can host/run many different workflows, and possibly contribute back.

So far I cannot get elastic search working, tho I haven't spent time trying to figure out why. 

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at WorkflowCore.Services.BackgroundTasks.QueueConsumer.Stop()
   at WorkflowCore.Services.WorkflowHost.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WorkflowCore.Services.WorkflowHost.Stop()
   at WorkflowCore.Services.WorkflowHost.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at TestWorkflowCore.Program.Main(String[] args) in C:\GitHub\WorkflowTesting\MyWorkflowTesting\TestWorkflowCore\Program.cs:line 17
```

I figure it's because I have 7.5.2 running.


Anyway, I went to look at the database structure, what's stored in there, etc. Due to it not following standard naming conventions I have to escape every table/column. Because I'm wondering if it's possible for me to use PostgreSQL or CloudSearch for the search index, and memcached for the distributed lock, so I can minimise what stuff I need until I move from memcached to redis later in the year, and CloudSearch to ElasticCache at the end of the year. 

So I'm not trying to tie my app into the WFC database structure. I'm just querying from datagrip to understand whats there.

**Comment by danielgerlag** [comment]
I don't currently have a memcached implementation for the backplane, or any other search implementations.  Everything is well abstracted, so other implementations can be easily plugged in.

**Comment by phillip-haydon** [comment]
I can see it's well abstracted which is why I'm wondering to myself if it's possible for me to do these things.

I'll chock the original question about PostgreSQL not following standards down to not knowing anything about Postgres.
