### ISSUE TITLE
Issue with EntityFrameworkPersistenceProvider

### ISSUE THREAD

**Issue by CraigEaston** [danielgerlag/workflow-core#515]
On the following line in my startup.cs I'm getting the error listed.

WorkflowCore.Interface.IWorkflowHost host = app.ApplicationServices.GetService<WorkflowCore.Interface.IWorkflowHost>();

I upgraded my solution from 1.9.2 to 3.1.4 and that is when the issue started.

System.TypeLoadException
  HResult=0x80131522
  Message=Method 'GetSubscriptions' in type 'WorkflowCore.Persistence.EntityFramework.Services.EntityFrameworkPersistenceProvider' from assembly 'WorkflowCore.Persistence.EntityFramework, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
  Source=WorkflowCore.Persistence.MySQL
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c__DisplayClass0_0.<UseMySQL>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at SHI.APIConsoleApprovalWorkFlow.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Projects\APIConsole\APIConsole.Workflow\APIConsoleApprovalWorkFlow\Startup.cs:line 115

**Comment by CraigEaston** [comment]
When I fall back to these versions, things work:
    <PackageReference Include="WorkflowCore" Version="2.0.0" />
    <PackageReference Include="WorkflowCore.Persistence.MySQL" Version="1.2.0" />
    <PackageReference Include="WorkflowCore.Providers.Redis" Version="2.0.0" />

**Comment by danielgerlag** [comment]
This is because the MySQL provider is out of date.  We need to publish a new version the works with the latest core library.

**Comment by JordanBrobyn** [comment]
> This is because the MySQL provider is out of date. We need to publish a new version the works with the latest core library.

I cloned a copy of your old instance of Persistence.MySQL, it seems to work with simply updating the EntityFramework and Pomelo nuget packages to the latest. Built fine for me. I haven't done a lot of testing, besides startup and ensuring the migrations took.

**Comment by danielgerlag** [comment]
I have updated the library... please try with the latest version
