### ISSUE TITLE
Auto delete complete workflows on redis

### ISSUE THREAD

**Issue by galipcevrik** [danielgerlag/workflow-core#692]
Hi @danielgerlag ,

When I enable this feature, it throws an error in the log records for each flow that succeeds, as follows. Is it possible for you to help solve this?

Much obliged!

MESSAGE
Unable to index workfow - 86e4810c-9979-4837-a95e-53ece7bcc035 - Value cannot be null. (Parameter 'value')

```
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at WorkflowCore.Providers.Redis.Services.RedisPersistenceProvider.GetWorkflowInstance(String Id) in ..\source\repos\workflow-core\src\providers\WorkflowCore.Providers.Redis\Services\RedisPersistenceProvider.cs:line 82
   at WorkflowCore.Services.BackgroundTasks.WorkflowConsumer.ProcessItem(String itemId, CancellationToken cancellationToken) in ..\source\repos\workflow-core\src\WorkflowCore\Services\BackgroundTasks\WorkflowConsumer.cs:line 46
   at WorkflowCore.Services.BackgroundTasks.WorkflowConsumer.ProcessItem(String itemId, CancellationToken cancellationToken) in ..\source\repos\workflow-core\src\WorkflowCore\Services\BackgroundTasks\WorkflowConsumer.cs:line 80
   at WorkflowCore.Services.BackgroundTasks.QueueConsumer.ExecuteItem(String itemId, EventWaitHandle waitHandle) in ..\source\repos\workflow-core\src\WorkflowCore\Services\BackgroundTasks\QueueConsumer.cs:line 131
```

**Comment by danielgerlag** [comment]
Yeah, I think we need to make the indexer aware of deleted workflows, and remove them from the index or do update the index in some other way... what are your thoughts?

**Comment by galipcevrik** [comment]
I did not have the opportunity to examine the indexing parts because of the workload. I will review it as soon as possible.

**Comment by ssougnez** [comment]
Not sure but it might be due to this: https://github.com/danielgerlag/workflow-core/issues/646 as the stack trace seems to be the same.
