### ISSUE TITLE
Exception on start host with EF Core 5 and Npgsql 5.0

### ISSUE THREAD

**Issue by Dumkin** [danielgerlag/workflow-core#697]
Exception:

```
System.AggregateException: One or more errors occurred. (Could not load type 'Microsoft.EntityFrameworkCore.NpgsqlDbContextOptionsExtensions' from assembly 'Npgsql.EntityFrameworkCore.PostgreSQL, Vers
ion=5.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.)
 ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.NpgsqlDbContextOptionsExtensions' from assembly 'Npgsql.EntityFrameworkCore.PostgreSQL, Version=5.0.0.0, Culture=neut
ral, PublicKeyToken=5d8b90d52f46fda7'.
   at WorkflowCore.Persistence.PostgreSQL.PostgresContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at WorkflowCore.Persistence.EntityFramework.Services.EntityFrameworkPersistenceProvider.EnsureStoreExists()
   at WorkflowCore.Services.WorkflowHost.StartAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WorkflowCore.Services.WorkflowHost.Start()
   at Aeb.LoanWorkflowService.Web.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in W:\Projects-HTC\LoanWorkflowService\Aeb.LoanWorkflowService.Web\Startup.cs:line 120
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.MethodInfoExtensions.InvokeWithoutWrappingExceptions(MethodInfo methodInfo, Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.Extensions.DependencyInjection.AutoRegisterMiddleware.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

In ConfigureServices
```
            services.AddWorkflow(c =>
            {
                c.UsePostgreSQL(databaseSettings.ConnectionString, true, true);
            });
```

In Configure()
```
            var host = app.ApplicationServices.GetService<IWorkflowHost>();
            host.RegisterWorkflow<AsyncAwaitWorkflow, CreditRequestModel>();
            host.Start();
```

Libs 
```

        <PackageReference Include="WorkflowCore.Persistence.PostgreSQL" Version="3.1.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0" />
        <PackageReference Include="WorkflowCore" Version="3.3.0" />
        <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="5.1.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.0" />
```

sdk net 5.0.100

**Comment by Dumkin** [comment]
sdk net 5.0.100
