### ISSUE TITLE
Upgrade to dotnet 5

### ISSUE THREAD

**Issue by evolvedlight** [danielgerlag/workflow-core#702]
Hi,

Is there a plan to merge https://github.com/danielgerlag/workflow-core/pull/695 in? Or would you prefer to keep the references on netstandard2.0? Or 2.1? 

Just wondering if there's anything I can do to help this happen.

Thanks.
Steve

**Comment by sandord** [comment]
I'm interested too since I get the following exception with .NET 5 rtm and the Npgsql.EntityFrameworkCore.PostgreSQL package:

    Could not load type 'Microsoft.EntityFrameworkCore.NpgsqlDbContextOptionsExtensions' from assembly 'Npgsql.EntityFrameworkCore.PostgreSQL, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
       at WorkflowCore.Persistence.PostgreSQL.PostgresContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder)
       at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
       at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
       at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
       at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
       at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
       at WorkflowCore.Persistence.EntityFramework.Services.EntityFrameworkPersistenceProvider.EnsureStoreExists()
       at WorkflowCore.Services.WorkflowHost.StartAsync(CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at WorkflowCore.Services.WorkflowHost.Start()
