### ISSUE TITLE
System.ObjectDisposedException: The collection has been disposed. Object name: 'BlockingCollection'.

### ISSUE THREAD

**Issue by narayansharmadotnet** [danielgerlag/workflow-core#744]
Hi, i am trying to setup the workflow core in my web api project (.net core 5.0) and i am getting this exception the moment the workflow starts with first step but cotinues to next step with same error and onto next one....

WorkflowCore.Services.BackgroundTasks.RunnablePoller: Information: Polling for runnable workflows
WorkflowCore.Services.BackgroundTasks.RunnablePoller: Information: Polling for unprocessed events
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.1\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
WorkflowCore.Services.WorkflowExecutor: Error: Workflow 2ae34549-fb4c-49d7-9065-10af71a2503a raised error on step 0 Message: The collection has been disposed.
Object name: 'BlockingCollection'.

System.ObjectDisposedException: The collection has been disposed.
Object name: 'BlockingCollection'.
   at System.Collections.Concurrent.BlockingCollection`1.CheckDisposed()
   at System.Collections.Concurrent.BlockingCollection`1.get_IsAddingCompleted()
   at WorkflowCore.Services.LifeCycleEventPublisher.PublishNotification(LifeCycleEvent evt)
   at WorkflowCore.Services.WorkflowExecutor.InitializeStep(WorkflowInstance workflow, WorkflowStep step, WorkflowExecutorResult wfResult, WorkflowDefinition def, ExecutionPointer pointer)
   at WorkflowCore.Services.WorkflowExecutor.Execute(WorkflowInstance workflow, CancellationToken cancellationToken)
WorkflowCore.Services.BackgroundTasks.WorkflowConsumer: Error: Error executing item 2ae34549-fb4c-49d7-9065-10af71a2503a - The collection has been disposed.
Object name: 'BlockingCollection'.

System.ObjectDisposedException: The collection has been disposed.
Object name: 'BlockingCollection'.
   at System.Collections.Concurrent.BlockingCollection`1.CheckDisposed()
   at System.Collections.Concurrent.BlockingCollection`1.get_IsAddingCompleted()
   at WorkflowCore.Services.LifeCycleEventPublisher.PublishNotification(LifeCycleEvent evt)
   at WorkflowCore.Services.ExecutionResultProcessor.HandleStepException(WorkflowInstance workflow, WorkflowDefinition def, ExecutionPointer pointer, WorkflowStep step, Exception exception)
   at WorkflowCore.Services.WorkflowExecutor.Execute(WorkflowInstance workflow, CancellationToken cancellationToken)
   at WorkflowCore.Services.BackgroundTasks.WorkflowConsumer.ProcessItem(String itemId, CancellationToken cancellationToken)
   at WorkflowCore.Services.BackgroundTasks.WorkflowConsumer.ProcessItem(String itemId, CancellationToken cancellationToken)
   at WorkflowCore.Services.BackgroundTasks.WorkflowConsumer.ProcessItem(String itemId, CancellationToken cancellationToken)
   at WorkflowCore.Services.BackgroundTasks.QueueConsumer.ExecuteItem(String itemId, EventWaitHandle waitHandle)
WorkflowCore.Services.WorkflowExecutor: Error: Workflow 2ae34549-fb4c-49d7-9065-10af71a2503a raised error on step 0 Message: The collection has been disposed.
Object name: 'BlockingCollection'.

System.ObjectDisposedException: The collection has been disposed.
Object name: 'BlockingCollection'.
   at System.Collections.Concurrent.BlockingCollection`1.CheckDisposed()
   at System.Collections.Concurrent.BlockingCollection`1.get_IsAddingCompleted()
   at WorkflowCore.Services.LifeCycleEventPublisher.PublishNotification(LifeCycleEvent evt)
   at WorkflowCore.Services.ExecutionResultProcessor.ProcessExecutionResult(WorkflowInstance workflow, WorkflowDefinition def, ExecutionPointer pointer, WorkflowStep step, ExecutionResult result, WorkflowExecutorResult workflowResult)
   at WorkflowCore.Services.WorkflowExecutor.ExecuteStep(WorkflowInstance workflow, WorkflowStep step, ExecutionPointer pointer, WorkflowExecutorResult wfResult, WorkflowDefinition def, CancellationToken cancellationToken)
   at WorkflowCore.Services.WorkflowExecutor.Execute(WorkflowInstance workflow, CancellationToken cancellationToken)
WorkflowCore.Services.BackgroundTasks.WorkflowConsumer: Error: Error executing item 2ae34549-fb4c-49d7-9065-10af71a2503a - The collection has been disposed.
Object name: 'BlockingCollection'.

System.ObjectDisposedException: The collection has been disposed. Object name: 'BlockingCollection'.
   at System.Collections.Concurrent.BlockingCollection`1.CheckDisposed()
   at System.Collections.Concurrent.BlockingCollection`1.get_IsAddingCompleted()
   at WorkflowCore.Services.LifeCycleEventPublisher.PublishNotification(LifeCycleEvent evt)
   at WorkflowCore.Services.ExecutionResultProcessor.HandleStepException(WorkflowInstance workflow, WorkflowDefinition def, ExecutionPointer pointer, WorkflowStep step, Exception exception)
   at WorkflowCore.Services.WorkflowExecutor.Execute(WorkflowInstance workflow, CancellationToken cancellationToken)
   at WorkflowCore.Services.BackgroundTasks.WorkflowConsumer.ProcessItem(String itemId, CancellationToken cancellationToken)
   at WorkflowCore.Services.BackgroundTasks.WorkflowConsumer.ProcessItem(String itemId, CancellationToken cancellationToken)
   at WorkflowCore.Services.BackgroundTasks.WorkflowConsumer.ProcessItem(String itemId, CancellationToken cancellationToken)
   at WorkflowCore.Services.BackgroundTasks.QueueConsumer.ExecuteItem(String itemId, EventWaitHandle waitHandle)
The thread 0x76e8 has exited with code 0 (0x0).
WorkflowCore.Services.BackgroundTasks.RunnablePoller: Information: Polling for runnable workflows
WorkflowCore.Services.BackgroundTasks.RunnablePoller: Information: Polling for unprocessed events
WorkflowCore.Services.WorkflowExecutor: Error: Workflow 2ae34549-fb4c-49d7-9065-10af71a2503a raised error on step 1 Message: The collection has been disposed.
Object name: 'BlockingCollection'.

I am using default in memory persistence and only have services.AddWorkflow() without any external depedency. Could you please point me to right direction on how i could troubleshoot this. Thank you.

**Comment by narayansharmadotnet** [comment]
I managed to debug the code and found that the LifeCycleEventPublisher (this implements IDisposable) is disposing _outbox (BlockingCollection<LifeCycleEvent>) during application start up for some reason, if i comment out _outbox.Dispose() i am able to run my workflow. Could you please advice why _outbox  is getting disposed in my application startup or if this is a bug that can be fixed in coming release ?

**Comment by narayansharmadotnet** [comment]
I am starting a workflow in my api controller that i have registered during application startup. I think the problem is when multiple api request are received the LifeCycleEventPublisher is getting disposed as this is registered as singleton (services.AddSingleton<ILifeCycleEventPublisher, LifeCycleEventPublisher>()). Changing this to AddScoped worked fine.

**Comment by danielgerlag** [comment]
What does your full IoC setup look like? (Making it scoped will break functionality, singletons should not by disposed unless you're doing explicitly?)

**Comment by narayansharmadotnet** [comment]
My api project set up is quite big but only thing i have added new is serviceCollection.AddWorkflow() and on application start up it calls the LifeCycleEventPublisher constructor followed by LifeCycleEventPublisher.Dispose method. I haven't added any other code to register workflow or workflow steps. Just one line code to add workflow and i can see the break point hitting  dipose method of LifeCycleEventPublisher

**Comment by narayansharmadotnet** [comment]
In ServiceCollectionExtensions 
Line 38 services.AddSingleton<ILifeCycleEventPublisher, LifeCycleEventPublisher>();
Line 60 services.AddTransient<IBackgroundTask>(sp => sp.GetService<ILifeCycleEventPublisher>());

Does it mean the ILifeCycleEventPublisher is transient ?

**Comment by narayansharmadotnet** [comment]
I had a warmup service code which was disposing IBackgroundTask which was causing the issue. Thanks for pointing me to the IoC setup which gave me a clue to resolve this.
